### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nalmadi** [nalmadi/fix8#149]
Unless I missed it, you don't seem to have any docs, and this will be important going forward. The paper will be able to serve as documentation for a limited time, but as the package matures you will want to be able to keep the docs up to date, so it's not good to rely on the paper for that purpose. There are packages that can help you generate documentation automatically that you can investigate.

**Comment by nalmadi** [comment]
https://youtu.be/b4iFyrLQQh4?si=Y6PtFiFchlmkbmf1

**Comment by brettmt13** [comment]
do we need to use sphinx? would pdoc suffice?

**Comment by brettmt13** [comment]
#171

**Comment by nalmadi** [comment]
@najam-tariq how did you generate the API documentation page?  What tool did you use?  I plan to regenerate it, how can I do that on my own?  Thanks!

**Comment by najam-tariq** [comment]
> @najam-tariq how did you generate the API documentation page? What tool did you use? I plan to regenerate it, how can I do that on my own? Thanks!

Hi @nalmadi, I used a library called pdoc: https://pdoc.dev/

**Comment by nalmadi** [comment]
Edited the manual here: https://docs.google.com/document/d/14g-kQfCTfn-jabcN50_mCkjD39DFVtT_sLlosPTREzQ/edit?usp=sharing
