### ISSUE TITLE
when cloning the repository it is too large >500MiB - figure out how to make it smaller

### ISSUE THREAD

**Issue by nalmadi** [nalmadi/fix8#195]
better way to store executables in repo, remove 1.22 GB history

**Comment by brettmt10** [comment]
these were the deleted files via the tool: https://rtyley.github.io/bfg-repo-cleaner/
command ran: `java -jar bfg.jar --strip-blobs-bigger-than 60M fix8`


Deleted files
-------------

        Filename                         Git id
        -----------------------------------------------------------------------
        Fix8_Mac.zip                   | 9a5b95db (96.1 MB)
        Fix8_Mac_v1.2.zip              | 45690869 (96.1 MB)
        Fix8_v1.1_onefile.zip          | b500a0b6 (68.1 MB)
        Fix8_v1.2-Windows.zip          | 3214be26 (82.1 MB)
        Fix8_v1.2_onefile-Windows.zip  | 864d4f4f (82.0 MB)
        Fix8_v1_onefile_exe.zip        | 876370be (66.2 MB)
        Fix8_v1_unpacked_exe.zip       | 19f27bff (66.5 MB)
        Fix8_v_1.2_Windows.zip         | 5472cb52 (81.9 MB)
        Fix8_v_1.2_onefile_Windows.zip | 075cec75 (81.7 MB)
        Fix9_v1_onefile_exe.zip        | 876370be (66.2 MB)
        Fix9_v1_unpacked_exe.zip       | 19f27bff (66.5 MB)
        datasets.zip                   | e069fae0 (61.1 MB)
        fix8_Mac.zip                   | 91b7c8d3 (97.0 MB)
        fix8_Mac_v1.2.zip              | 9a5b95db (96.1 MB), 91b7c8d3 (97.0 MB)
        fix8_v1.1.zip                  | 3643ca30 (68.2 MB)
        fix8_v1.2_Mac_experiment2.zip  | 3ef2008d (98.2 MB)
