### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by BaiYunpeng1949** [nalmadi/fix8#197]
Not raising an issue, just want to say thank you for the nice tool! Looking forward to using the Linux tool (better with a headless mode). Now I have to scp my files from the server lol.

**Comment by BaiYunpeng1949** [comment]
Sorry, just spot Windows download issue 
![image](https://github.com/user-attachments/assets/4db28fc2-3424-4666-922c-f07ec9a40f44)

**Comment by nalmadi** [comment]
Thanks for the feedback @BaiYunpeng1949!  You can find the latest version of Fix8 executables here: https://github.com/nalmadi/fix8/tree/main/executables

it takes a couple of minutes to load the first time you run it but it's faster after that.  Please let me know if you experience any problems running the code.

Also, if you are interested in using Fix8 as an API without the GUI, you should check this page: https://fix8-eye-tracking.github.io/mini_emtk.html

Don't hesitate to reach out if you have any questions!

**Comment by BaiYunpeng1949** [comment]
> Thanks for the feedback @BaiYunpeng1949! You can find the latest version of Fix8 executables here: https://github.com/nalmadi/fix8/tree/main/executables
> 
> it takes a couple of minutes to load the first time you run it but it's faster after that. Please let me know if you experience any problems running the code.
> 
> Also, if you are interested in using Fix8 as an API without the GUI, you should check this page: https://fix8-eye-tracking.github.io/mini_emtk.html
> 
> Don't hesitate to reach out if you have any questions!

**Comment by nalmadi** [comment]
Glad to hear that!
